### ISSUE TITLE
Answer count addon

### ISSUE THREAD

**Issue by dedu6ka** [lionawurscht/anki_addon_answer_count#1]
Would be nice to count  the 'Pass' and 'Fail' reps for the Graduating interval.  
They could be  tallied in a Table for the last 30 days.  
  
This info would tell us if the "Learning phase" is adequate or insufficient to get the 80 - 90% retention;  one of three factors, listed below, will be adjusted and tested again.  

The following parameters will be 'static':  
* Deck ( Study Subject)  
* Note_Type ( Cloze or other).  
* Card Type ( card-1 only would be tracked )  
* Card Status ( learning )  

The user would decide which of the factors below he wants to change first ( one at a time of course):  
* Set of Learning Steps.  
* Batch size ( number of cards being tested together).  
* Were the batch of cards recited ( prior to Testing ) or not.  

The previous cumulative count could be Reset (or Saved / printed ) and a new counting will begin.  

PS, If the process turns out to be practical, it could be extended to 'discover' the near-optimum Second Learning step;   
and the Relearn step ( or the New Interval ).  
Cheers

**Comment by lionawurscht** [comment]
Hey, thanks for writing. I am afraid that your proposal, which admittedly I don't get entirely, seems to extend beyond the scope of this addon. This addon is simply meant to add counts of the expected answers to an anki question to the question and is mostly meant for my personal use. Maybe you could bring your issue up with the developer of anki itself of one of the bigger addon developers?
